### ISSUE TITLE
[WIP] Mutation changes

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#263]
So this is still WIP, but I thought I open an issue about this early.

Current WIP mutation header at Storyscript: https://github.com/storyscript/storyscript/blob/master/storyscript/compiler/semantics/functions/HubMutations.py

List
----

- should return itself instead of None for e.g. `sort` or `reverse` (allows chaining)
- `index` is an anti-pattern (two ways to do the same thing)

Dict
-----

- `get` is an anti-pattern  (two ways to do the same thing)
- `length` instead of `size` (for consistency)

Number
---------

- rename to `Int` or `Integer` (an integer has different mutations than a float)

Though this isn't strictly required as long as the number type offers the joined set of Int and Float.

Float
-----

I have a few potential methods here:

- round
- ceil
- floor
- cos
- sin
- tan
etc.

**Comment by judepereira** [comment]
Already in master.
