### ISSUE TITLE
Check for a maximum call stack size to avoid endless recursions

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#342]
The engine should detect endless recursion by limiting the call stack and bail out.

**Comment by chrisstpierre** [comment]
Same for loops yeah? What’s a good stack size for this? :)

Ok edge case - what if this is a purposefully repeating loop / recursion with blocking statements inside to slow it down... like an event loop... maybe a game engine in story script 👍

**Comment by wilzbach** [comment]
> Same for loops yeah?

Loops don't open a stack d
frame and consume more memory. Also, foreach loops have a finite amount of elements. We have `while` blocks though and `while True` can of course result in deadlocks, this probably should be dealt with a general timeout as its a valid usage pattern.

> Ok edge case - what if this is a purposefully repeating loop / recursion

That's why there will a sensible high limit.
It depends a bit on what our engine can handle, but anything between 100-1000 should be reasonable.

**Comment by chrisstpierre** [comment]
Ok cool thanks seb
