### ISSUE TITLE
Move the database repo into the engine

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#355]
PR's to the engine often update the [database](https://github.com/storyscript/database) which clearly shows their dependence.

Examples:
- https://github.com/storyscript/database/pull/76
- https://github.com/storyscript/database/pull/75
- https://github.com/storyscript/database/pull/74
- https://github.com/storyscript/database/pull/72
...

Also, https://github.com/storyscript/platform-engine/issues/354 will require starting the Postgres database in the CI, so the dependence on the repo is evident. Hence, I suggest we move the database into this repo.

**Comment by judepereira** [comment]
Closing since:
1. The engine is not the only one dictating changes to the database
2. The database contains other items, such as RLS
3. The dashboard will alter the database as well, with new tables for billing, user management, etc.
