### ISSUE TITLE
Service output contracts should include booleans

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#367]
When a service returns a `boolean`, but an `int` is expected it should fail.
At the very least, we should define the behavior in the testsuite and not comment it out:

https://github.com/storyscript/platform-engine/pull/365/files#diff-b5dd8c5830d5eb3bd6cee33f3a8fa15aR29

**Comment by judepereira** [comment]
@wilzbach so python doesn't differentiate between boolean and int for 1 and 0. How do you propose we solve this? Note that we do check for declared boolean, but returned int: https://github.com/storyscript/platform-engine/pull/365/files#diff-b5dd8c5830d5eb3bd6cee33f3a8fa15aR45

**Comment by wilzbach** [comment]
tl;dr do not use Python data types directly without a wrapper.
See also: https://github.com/storyscript/platform-engine/issues/327

**Comment by judepereira** [comment]
Ah yes, go it. That's a precursor.
