### ISSUE TITLE
Static tmp_dir for storyscript execution

### ISSUE THREAD

**Issue by TonyRice** [storyscript/runtime#400]
The file service currently creates a temporary directory using the execution_id. This causes problems that make it impossible for a story to access data written at first startup. For example:

```
file mkdir path: "/tmp"

http server as client
  when client listen method:"post" path:"/test" as r
    file write path:"/tmp/file.zip" content: r.data[1]
    r write content: "Hello World"
```

will throw the following:

```
Failed to write to file: [Errno 2] No such file or directory: '/tmp/story.43d98d01-1650-4c3d-8ca7-8998ba9560da/tmp/file.zip'
    at line 3: when client listen method:"post" path:"/test" as r (in hello.story)
    at line 4: file write path:"/tmp/file.zip" content: r.data[1] (in hello.story)
```
This is due to the fact that when a request is triggered, the execution-id is different. It might make sense to utilize the app_uuid when using the file service.

**Comment by judepereira** [comment]
Closed with #481.
