### ISSUE TITLE
Service names are no longer present in the logs

### ISSUE THREAD

**Issue by judepereira** [storyscript/runtime#410]
@anukul Looks like post your service_usage deployment, the service names are no longer being shown in the logs.
Reproducible by:
```
story logs -f -s -a stories
```
```
Jul 28 16:22:30 UNKNOWN      unknown: 10.56.5.37 - - [28/Jul/2019 14:22:30] "POST /push HTTP/1.1" 202 -
Jul 28 16:22:40 UNKNOWN      unknown: 10.56.6.1 - - [28/Jul/2019 14:22:40] "GET /health HTTP/1.1" 200 -
Jul 28 16:23:10 UNKNOWN      unknown: 10.56.6.1 - - [28/Jul/2019 14:23:10] "GET /health HTTP/1.1" 200 -
```

The level is UNKNOWN, which is okay, but the other `unknown` in lower case is supposed to be the service name.

**Comment by anukul** [comment]
Oh, I didn't notice that the `b16-service-name` label was being used in the logs, added it back in.

**Comment by judepereira** [comment]
@anukul perhaps fix it in storyscript/logstreamer? b16 was just a placeholder since we didn't have a legit uuid for (service, tag) earlier.
