### ISSUE TITLE
Add support for the throw keyword

### ISSUE THREAD

**Issue by TonyRice** [storyscript/runtime#440]
Currently, the runtime does not support the function "throw". We need to add support for this to properly throw exceptions when catching them.

**Comment by judepereira** [comment]
+1 to this - we should add this as a follow up PR of the open try/catch.

**Comment by wilzbach** [comment]
Let's only support strings for now. We will update the compiler to enforce this for us (-> https://github.com/storyscript/storyscript/issues/1099).

**Comment by wilzbach** [comment]
> We will update the compiler to enforce this for us (-> storyscript/storyscript#1099), so you don't need to worry about special cases.

Updated in https://github.com/storyscript/storyscript/pull/1101 and the compiler will disallow this starting with 0.24

**Comment by judepereira** [comment]
Closed with #444 .
