### ISSUE TITLE
Immutable mutations

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#468]
tl;dr: builtins don't shouldn't modify the object, but return their changes as copy.

https://github.com/storyscript/runtime/pull/464 does a few updates, but other methods like `append` or `prepend` need to be updated.

Full list: https://github.com/storyscript/hub-sdk-python/blob/master/storyhub/engine/Builtins.py

**Comment by judepereira** [comment]
@TonyRice will you be doing this this sprint? If yes, please add it to the current sprint. If not, please unassign yourself (so that somebody else can take over when free).
