### ISSUE TITLE
requests.structures.CaseInsensitiveDict do not support map mutations

### ISSUE THREAD

**Issue by judepereira** [storyscript/runtime#561]
Unsupported data type <class 'requests.structures.CaseInsensitiveDict'> for mutation contains
got this on this line:
request.headers.contains(key:"referer")

// cc @JeanBarriere

**Comment by wilzbach** [comment]
@jude that's why you want to have special data types in the runtime and enforce that only those are passed into the interpreter. I hope this continues to make my case ;-)
