### ISSUE TITLE
Implement List.join

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#588]
https://github.com/storyscript/hub-sdk-python/pull/55

Should stringify each element and then concatenate them with `sep`.

**Comment by anukul** [comment]
Does the `story-hub` package need an update?

**Comment by wilzbach** [comment]
Yes I will update it tonight.

**Comment by wilzbach** [comment]
https://github.com/storyscript/storyscript/releases/tag/0.25.1
-> already in master https://github.com/storyscript/runtime/pull/605
