### ISSUE TITLE
Support 'output: none' 

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#621]
https://github.com/microservices/openmicroservices.org/pull/150

See also: https://github.com/storyscript/runtime/issues/542

**Comment by anukul** [comment]
Support how? Can you please describe the expected behavior?

For example, we already have tests for this from the linked PR:

https://github.com/storyscript/runtime/blob/4d74766b1f1a5bd709ee8e3b873b4b2023ead2b4/tests/unit/omg/ServiceOutputValidator.py#L42-L44

**Comment by wilzbach** [comment]
Uhm so what happened here was the original PR implemented the spec at that time incorrectly. The spec allowed `output: none` and the recent spec PR changed it to `output: ... type: none`.

So we can close this one here.
