### ISSUE TITLE
Add a writeJSON method to the 'http' module

### ISSUE THREAD

**Issue by wilzbach** [storyscript/runtime#626]
```
request write content:(json stringify content:queries)
```

is very common. I think we should provide a convenience `writeJSON` a la:

```
request writeJSON content:queries
```

**Comment by daaAd1** [comment]
Hi, I would like to work on this. :)

**Comment by wilzbach** [comment]
@daaAd1 that's very cool to hear!

You can add new methods to the `http` module here:

https://github.com/storyscript/http/blob/master/microservice.yml

and I think in the source it would be this class then:

https://github.com/storyscript/http/blob/master/app/handlers/Exec.py#L262

**Comment by daaAd1** [comment]
Created pull request in http repo [here](https://github.com/storyscript/http/pull/55) . Not sure if there is anything else that needs to be changed in other repos.
